FROM bicf/bicfbase:1.1
LABEL author="Jon Gesell"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y openjdk-11-jdk openjdk-11-jre

RUN wget https://downloads.sourceforge.net/project/bbmap/BBMap_38.67.tar.gz
RUN tar -xvzf BBMap_38.67.tar.gz
ENV PATH=/bbmap/:${PATH}

VOLUME /var/tmp/results
VOLUME /var/tmp/data
