FROM ubuntu:18.04
LABEL author="Jon Gesell"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y --fix-missing
RUN apt-get upgrade -y
RUN apt-get dist-upgrade -y
RUN apt-get autoremove -y
RUN apt-get update -y --fix-missing
RUN apt-get upgrade -y
RUN apt-get install -y gcc g++ apt-utils wget gzip pigz perl pbzip2

VOLUME /var/tmp/results
VOLUME /var/tmp/data
