FROM bicf/bcl2fastq2.17:2.0.0
LABEL author="Jon Gesell"

#Install the CellRanger version
#NOTE: This link expires every 10 minutes, needs to be refreshed every time.
RUN wget -O cellranger-3.0.2.tar.gz "http://cf.10xgenomics.com/releases/cell-exp/cellranger-3.0.2.tar.gz?Expires=1587022863&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cDovL2NmLjEweGdlbm9taWNzLmNvbS9yZWxlYXNlcy9jZWxsLWV4cC9jZWxscmFuZ2VyLTMuMC4yLnRhci5neiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4NzAyMjg2M319fV19&Signature=l4m2l~T0cNnlHByiuspNYkyojkP1ccPtO9-lxtxjVehhW06sAOqqUIUSNDhU2O~HPk6Z9UhFTaGOSj7QyQ5eSsIItipzoynMJdqy~hLKYf0bNsy6zp06~6Mjq2CPMHRRBNqwwc5ENFzcVhQFhj92CCq43XPXkO3davOLYbV4VaeCKj~nGcwf1WMNDK~Lm3S0haw~YnXXF32tji2pOw-0sQofNy-IsOWoMYb175WcDdGVtoU2ynODl763xRvrtKVGhYmdpj2eKqoC7TjkNm09hCeRgtkEnvjHKrfxlWcCflu-7McwonuoCmJD-pKpiBnGom9xxfPSIiPiKZnAA2jgaw__&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA" && \
  tar -xzvf cellranger-3.0.2.tar.gz --directory /opt && \
  rm cellranger*.tar.gz;

ENV PATH="$PATH:/opt/cellranger-3.0.2"

ENTRYPOINT ["cellranger"]
