FROM bicf/bicfbase:2.0.0
LABEL author="Jon Gesell"

RUN add-apt-repository ppa:openjdk-r/ppa && \
  apt-get update --fix-missing -y && \
  apt-get install -y openjdk-12-jdk-headless;

ENTRYPOINT ["java"]
