FROM bicf/bicfbase:1.2
LABEL author="Jon Gesell"

RUN apt-get install -y openjdk-11-jdk openjdk-11-jre

RUN wget https://downloads.sourceforge.net/project/bbmap/BBMap_38.67.tar.gz && \
  tar -xvzf BBMap_38.67.tar.gz && \
  rm BBMap_38.67.tar.gz
ENV PATH=/bbmap/:${PATH}
