FROM bicf/bicfbase:1.1
LABEL author="Jon Gesell"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y curl git make default-jdk python3

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -p /miniconda -b
ENV PATH=/miniconda/bin:${PATH}
RUN conda config --add channels defaults
RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge
RUN conda update -y conda
RUN conda install -c bioconda fastqc

VOLUME /var/tmp/results
VOLUME /var/tmp/data
